name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          volta-version: 1.0.8
      # failing tests
      - name: Run tests
        run: yarn test
